name: OmniSharp-VSCode CI

on:
  push:
    branches: [ master, feature/** ]

  pull_request:
    branches: [ master, feature/** ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Install Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
          npm ci
          npm i -g gulp

    - name: Compile
      run: npm run compile

    - name: Prepublish VSIXs
      run: npm run vscode:prepublish

    - name: Build VSIXs
      run: gulp 'vsix:release:package'

    - name: Upload neutral build artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./vsix/csharp-*.vsix
        name: csharp-neutral.vsix

    - name: Upload platform-specific build artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./vsix/csharp-${{ runner.os == 'macOS' && 'darwin' || 'linux' }}-*-*.vsix
        name: csharp-${{ runner.os == 'macOS' && 'darwin' || 'linux' }}.vsix